PREFIX admin: <http://webns.net/mvcb/>
PREFIX ad: <http://schemas.talis.com/2005/address/schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX ns:  <http://smartcity.linkeddata.es/ontology/TerrazasMadrid/>
PREFIX admingeo: <http://data.ordnancesurvey.co.uk/ontology/admingeo/>

SELECT ?district
WHERE{
	?district rdf:type admingeo:District.
}

