PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX vocab: <http://www.preventbicyleaccidents-app.es/group02/ontology/bicycletrafficaccident#>

SELECT DISTINCT
        ?Object 
    WHERE {
        ?Accident vocab:hasWeather ?Object.
    }

(rdflib.term.Literal('Despejado'),)
(rdflib.term.Literal(''),)
(rdflib.term.Literal('Nublado'),)
(rdflib.term.Literal('Lluvia débil'),)
(rdflib.term.Literal('Se desconoce'),)
(rdflib.term.Literal('LLuvia intensa'),)