PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

	SELECT DISTINCT
        ?Provincia
    WHERE {
        ?Subject ?Provincia ?Object .
    }
    ORDER BY asc(?Provincia)
	
#http://calidadAire.com#ano
#http://calidadAire.com#dia
#http://calidadAire.com#fecha
#http://calidadAire.com#h01
#http://calidadAire.com#h010
#http://calidadAire.com#h011
#http://calidadAire.com#h012
#http://calidadAire.com#h013
#http://calidadAire.com#h014
#http://calidadAire.com#h015
#http://calidadAire.com#h016
#http://calidadAire.com#h017
#http://calidadAire.com#h018
#http://calidadAire.com#h019
#http://calidadAire.com#h02
#http://calidadAire.com#h020
#http://calidadAire.com#h021
#http://calidadAire.com#h022
#http://calidadAire.com#h023
#http://calidadAire.com#h024
#http://calidadAire.com#h03
#http://calidadAire.com#h04
#http://calidadAire.com#h05
#http://calidadAire.com#h06
#http://calidadAire.com#h07
#http://calidadAire.com#h08
#http://calidadAire.com#h09
#http://calidadAire.com#mes
#http://calidadAire.com#mide
#http://calidadAire.com#refEstacion
#http://calidadAire.com#refMagnitud
#http://calidadAire.com#refMunicipio
#http://calidadAire.com#refProvincia
#http://calidadAire.com#refPunto
#http://calidadAire.com#tieneEstacion
#http://calidadAire.com#tieneMedicion
#http://calidadAire.com#tieneMunicipio
#http://calidadAire.com#tienePuntoMuestreo
#http://calidadAire.com#valido1
#http://calidadAire.com#valido10
#http://calidadAire.com#valido11
#http://calidadAire.com#valido12
#http://calidadAire.com#valido13
#http://calidadAire.com#valido14
#http://calidadAire.com#valido15
#http://calidadAire.com#valido16
#http://calidadAire.com#valido17
#http://calidadAire.com#valido18
#http://calidadAire.com#valido19
#http://calidadAire.com#valido2
#http://calidadAire.com#valido20
#http://calidadAire.com#valido21
#http://calidadAire.com#valido22
#http://calidadAire.com#valido23
#http://calidadAire.com#valido24
#http://calidadAire.com#valido3
#http://calidadAire.com#valido4
#http://calidadAire.com#valido5
#http://calidadAire.com#valido6
#http://calidadAire.com#valido7
#http://calidadAire.com#valido8
#http://calidadAire.com#valido9
#http://www.w3.org/1999/02/22-rdf-syntax-ns#type


SELECT DISTINCT
        ?Properties
    WHERE {
        ?Properties ?Municipio ?Object .
    }
    ORDER BY asc(?Properties)
	
#http://calidadAire.com/1
#http://calidadAire.com/10
#http://calidadAire.com/102
#http://calidadAire.com/12
#http://calidadAire.com/120
#http://calidadAire.com/123
#http://calidadAire.com/13
#http://calidadAire.com/133
#http://calidadAire.com/14
#http://calidadAire.com/148
#http://calidadAire.com/16
#http://calidadAire.com/161
#http://calidadAire.com/171
#http://calidadAire.com/180
#http://calidadAire.com/2
#http://calidadAire.com/20
#http://calidadAire.com/2021-10-1
#http://calidadAire.com/28
#http://calidadAire.com/28005002-1-38
#http://calidadAire.com/28005002-10-49
#http://calidadAire.com/28005002-12-8
#http://calidadAire.com/28005002-14-6
#http://calidadAire.com/28005002-6-48
#http://calidadAire.com/28005002-7-8
#http://calidadAire.com/28005002-8-8
#http://calidadAire.com/28005002-9-49
#http://calidadAire.com/28006004-10-49
#http://calidadAire.com/28006004-12-8
#http://calidadAire.com/28006004-14-6
#http://calidadAire.com/28006004-20-59
#http://calidadAire.com/28006004-30-59
#http://calidadAire.com/28006004-42-2
#http://calidadAire.com/28006004-431-59
#http://calidadAire.com/28006004-44-2
#http://calidadAire.com/28006004-7-8
#http://calidadAire.com/28006004-8-8
#http://calidadAire.com/28007004-12-8
#http://calidadAire.com/28007004-14-6
#http://calidadAire.com/28007004-7-8
#http://calidadAire.com/28007004-8-8
#http://calidadAire.com/28007004-9-49
#http://calidadAire.com/28009001-12-8
#http://calidadAire.com/28009001-14-6
#http://calidadAire.com/28009001-7-8
#http://calidadAire.com/28009001-8-8
#http://calidadAire.com/28009001-9-49
#http://calidadAire.com/28013002-10-49
#http://calidadAire.com/28013002-12-8
#http://calidadAire.com/28013002-14-6
#http://calidadAire.com/28013002-7-8
#http://calidadAire.com/28013002-8-8
#http://calidadAire.com/28014002-10-49
#http://calidadAire.com/28014002-12-8
#http://calidadAire.com/28014002-14-6
#http://calidadAire.com/28014002-7-8
#http://calidadAire.com/28014002-8-8
#http://calidadAire.com/28016001-1-38
#http://calidadAire.com/28016001-10-49
#http://calidadAire.com/28016001-12-8
#http://calidadAire.com/28016001-14-6
#http://calidadAire.com/28016001-20-59
#http://calidadAire.com/28016001-30-59
#http://calidadAire.com/28016001-42-2
#http://calidadAire.com/28016001-431-59
#http://calidadAire.com/28016001-44-2
#http://calidadAire.com/28016001-6-48
#http://calidadAire.com/28016001-7-8
#http://calidadAire.com/28016001-8-8
#http://calidadAire.com/28016001-9-49
#http://calidadAire.com/28045002-10-49
#http://calidadAire.com/28045002-12-8
#http://calidadAire.com/28045002-14-6
#http://calidadAire.com/28045002-6-48
#http://calidadAire.com/28045002-7-8
#http://calidadAire.com/28045002-8-8
#http://calidadAire.com/28047002-1-38
#http://calidadAire.com/28047002-12-8
#http://calidadAire.com/28047002-14-6
#http://calidadAire.com/28047002-20-59
#http://calidadAire.com/28047002-30-59
#http://calidadAire.com/28047002-42-2
#http://calidadAire.com/28047002-431-59
#http://calidadAire.com/28047002-44-2
#http://calidadAire.com/28047002-7-8
#http://calidadAire.com/28047002-8-8
#http://calidadAire.com/28047002-9-49
#http://calidadAire.com/28049003-10-49
#http://calidadAire.com/28049003-12-8
#http://calidadAire.com/28049003-14-6
#http://calidadAire.com/28049003-7-8
#http://calidadAire.com/28049003-8-8
#http://calidadAire.com/28049003-9-49
#http://calidadAire.com/28058004-10-49
#http://calidadAire.com/28058004-12-8
#http://calidadAire.com/28058004-14-6
#http://calidadAire.com/28058004-20-59
#http://calidadAire.com/28058004-30-59
#http://calidadAire.com/28058004-42-2
#http://calidadAire.com/28058004-431-59
#http://calidadAire.com/28058004-44-2
#http://calidadAire.com/28058004-7-8
#http://calidadAire.com/28058004-8-8
#http://calidadAire.com/28065014-10-49
#http://calidadAire.com/28065014-12-8
#http://calidadAire.com/28065014-14-6
#http://calidadAire.com/28065014-7-8
#http://calidadAire.com/28065014-8-8
#http://calidadAire.com/28065014-9-49
#http://calidadAire.com/28067001-10-49
#http://calidadAire.com/28067001-12-8
#http://calidadAire.com/28067001-14-6
#http://calidadAire.com/28067001-7-8
#http://calidadAire.com/28067001-8-8
#http://calidadAire.com/28074007-10-49
#http://calidadAire.com/28074007-12-8
#http://calidadAire.com/28074007-14-6
#http://calidadAire.com/28074007-7-8
#http://calidadAire.com/28074007-8-8
#http://calidadAire.com/28074007-9-49
#http://calidadAire.com/28080003-10-49
#http://calidadAire.com/28080003-12-8
#http://calidadAire.com/28080003-14-6
#http://calidadAire.com/28080003-7-8
#http://calidadAire.com/28080003-8-8
#http://calidadAire.com/28092005-1-38
#http://calidadAire.com/28092005-10-49
#http://calidadAire.com/28092005-12-8
#http://calidadAire.com/28092005-14-6
#http://calidadAire.com/28092005-6-48
#http://calidadAire.com/28092005-7-8
#http://calidadAire.com/28092005-8-8
#http://calidadAire.com/28102001-1-38
#http://calidadAire.com/28102001-10-49
#http://calidadAire.com/28102001-12-8
#http://calidadAire.com/28102001-14-6
#http://calidadAire.com/28102001-6-48
#http://calidadAire.com/28102001-7-8
#http://calidadAire.com/28102001-8-8
#http://calidadAire.com/28120001-10-49
#http://calidadAire.com/28120001-12-8
#http://calidadAire.com/28120001-14-6
#http://calidadAire.com/28120001-7-8
#http://calidadAire.com/28120001-8-8
#http://calidadAire.com/28120001-9-49
#http://calidadAire.com/28123002-10-49
#http://calidadAire.com/28123002-12-8
#http://calidadAire.com/28123002-14-6
#http://calidadAire.com/28123002-7-8
#http://calidadAire.com/28123002-8-8
#http://calidadAire.com/28133002-10-49
#http://calidadAire.com/28133002-12-8
#http://calidadAire.com/28133002-14-6
#http://calidadAire.com/28133002-7-8
#http://calidadAire.com/28133002-8-8
#http://calidadAire.com/28148004-10-49
#http://calidadAire.com/28148004-12-8
#http://calidadAire.com/28148004-14-6
#http://calidadAire.com/28148004-7-8
#http://calidadAire.com/28148004-8-8
#http://calidadAire.com/28148004-9-49
#http://calidadAire.com/28161001-12-8
#http://calidadAire.com/28161001-14-6
#http://calidadAire.com/28161001-7-8
#http://calidadAire.com/28161001-8-8
#http://calidadAire.com/28161001-9-49
#http://calidadAire.com/28171001-1-38
#http://calidadAire.com/28171001-10-49
#http://calidadAire.com/28171001-12-8
#http://calidadAire.com/28171001-14-6
#http://calidadAire.com/28171001-6-48
#http://calidadAire.com/28171001-7-8
#http://calidadAire.com/28171001-8-8
#http://calidadAire.com/28171001-9-49
#http://calidadAire.com/28180001-12-8
#http://calidadAire.com/28180001-14-6
#http://calidadAire.com/28180001-7-8
#http://calidadAire.com/28180001-8-8
#http://calidadAire.com/28180001-9-49
#http://calidadAire.com/3
#http://calidadAire.com/30
#http://calidadAire.com/4
#http://calidadAire.com/42
#http://calidadAire.com/431
#http://calidadAire.com/44
#http://calidadAire.com/45
#http://calidadAire.com/47
#http://calidadAire.com/49
#http://calidadAire.com/5
#http://calidadAire.com/58
#http://calidadAire.com/6
#http://calidadAire.com/65
#http://calidadAire.com/67
#http://calidadAire.com/7
#http://calidadAire.com/74
#http://calidadAire.com/8
#http://calidadAire.com/80
#http://calidadAire.com/9
#http://calidadAire.com/92