# -*- coding: utf-8 -*-
"""Task06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZcifCYPcdx2SFzSvzLHEzPuRISczZ2It

**Task 06: Modifying RDF(s)**
"""

#!pip install rdflib 
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials"

"""Leemos el fichero RDF de la forma que lo hemos venido haciendo"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example5.rdf", format="xml")

"""Create a new class named Researcher"""

ns = Namespace("http://somewhere#")
g.add((ns.Researcher, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.1: Create a new class named "University"**

"""

# TO DO
# Visualize the results
g.add((ns.University, RDF.type, RDFS.Class))
print("**TASK 6.1: Create a new class named \"University\"**")
print("Resulting graph:")
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.2: Add "Researcher" as a subclass of "Person"**"""

# TO DO
# Visualize the results
g.add((ns.Researcher, RDF.type, ns.Person))
print("\n\n**TASK 6.2: Add \"Researcher\" as a subclass of \"Person\"**")
print("Resulting graph:")
for s, p, o in g:
  print(s,p,o)
print("\nSubClass relations:")
for s, p, o in g.triples((None,RDFS.subClassOf,None)):
  print(s,p,o)

"""**TASK 6.3: Create a new individual of Researcher named "Jane Smith"**"""

# TO DO
# Visualize the results
VCARD=Namespace("http://www.w3.org/2001/vcard-rdf/3.0/")
g.add((ns.JaneSmith, RDF.type, ns.Researcher))
print("\n\n**TASK 6.3: Create a new individual of Researcher named \"Jane Smith\"**")
print("Resulting graph:")
for s, p, o in g:
  print(s,p,o)
print("\nResearchers:")
for s, p, o in g.triples((None,RDF.type,ns.Researcher)):
  print(s)

"""**TASK 6.4: Add to the individual JaneSmith the fullName, given and family names**"""

# TO DO
# Visualize the results
g.add((ns.JaneSmith, VCARD.FN, Literal("Jane Smith")))
g.add((ns.JaneSmith, VCARD.Given, Literal("Jane")))
g.add((ns.JaneSmith, VCARD.Family, Literal("Smith")))
print("\n\nTASK 6.4: Add to the individual JaneSmith the fullName, given and family names**")
print("Resulting graph:")
for s, p, o in g:
  print(s,p,o)
print("\nFull names:")
for s, p, o in g.triples((None,VCARD.FN,None)):
  print(" - ",o)
print("\nGiven names:")
for s, p, o in g.triples((None,VCARD.Given,None)):
  print(" - ",o)
print("\nFamily names:")
for s, p, o in g.triples((None,VCARD.Family,None)):
  print(" - ",o)

"""**TASK 6.5: Add UPM as the university where John Smith works**"""

# TO DO
# Visualize the results
g.add((ns.UPM, RDF.type, ns.University))
g.add((ns.JohnSmith, VCARD.Work, ns.UPM))
print("\n\n**TASK 6.5: Add UPM as the university where John Smith works**")
print("Resulting graph:")
for s, p, o in g:
  print(s,p,o)
print("\nPeople(not necessarily people) working in UPM:")
for s, p, o in g.triples((None,VCARD.Work,ns.UPM)):
  print(s)