PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dbo: <http://www.smartcity.madrid.es/mobility/ontology/>

SELECT DISTINCT ?b
WHERE{
    ?b rdf:type dbo:Bus.
    ?b dbo:BARRIO "Embajadores". 
    ?b dbo:DISTRITO "Centro". 
    ?b dbo:LINEAS "T32".
}

SELECT DISTINCT ?metrostation
WHERE{
    ?metrostation rdf:type dbo:Metro.
    ?metrostation dbo:BARRIO "Embajadores". 
}

SELECT DISTINCT ?Tlight_id 
WHERE{
    ?Tlight_id rdf:type dbo:TrafficLight.
    ?Tlight_id dbo:DISTRITO "1". 
}

SELECT DISTINCT ?dis
WHERE{
    ?dis rdf:type dbo:Wards.
    ?dis dbo:hasMetro "EMBAJADORES". 
}

