PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dbo: <http://www.traffic-accidents.linkeddata.es/Accidentes#>


SELECT  ?accidente
WHERE{
    ?accidente rdf:type dbo:Accident.
    ?accidente dbo:hasDistrict ?district.
    ?district owl:sameAs "https://wikidata.org/entity/Q2076109".
}

SELECT DISTINCT ?accidente ?distrito ?date
WHERE{
    ?accidente rdf:type dbo:Accident.
    ?accidente dbo:hasDistrict ?district.
    ?district  rdf:type dbo:District.
    ?district dbo:hasDistrict "Retiro".
    ?accidente dbo:hasDate "2021-05-18"^^xsd:date.

}


SELECT DISTINCT ?accidente
WHERE{
    ?accidente rdf:type dbo:Accident.
    ?accidente dbo:hasAddress ?address. 
    ?accidente dbo:hasWeather "Despejado". 
    ?address dbo:hasAddress "Calle De Antonio López"
}

SELECT DISTINCT ?accidente ?distrito
WHERE{
    ?accidente rdf:type dbo:Accident.
    ?accidente dbo:hasDistrict ?district.
    ?district  rdf:type dbo:District.
    ?district dbo:hasDistrict ?distrito.

}


SELECT Distinct  ?calle ?enlace 
WHERE{
    ?accident rdf:type dbo:Accident.
    
    ?accident dbo:hasAddress ?address.
    ?address rdf:type dbo:Address.
    ?address dbo:hasAddress ?calle.
    OPTIONAL { ?address owl:sameAs ?enlace}.
    
    ?accident dbo:hasWeather "Nublado".
  
    ?accident dbo:hasDistrict ?district.
    ?district rdf:type dbo:District.
    ?district dbo:hasDistrict "Centro".
}
