PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX fountain: <http://fuent.example.com/fountain/>
PREFIX district: <http://dist.example.com/district/>

SELECT ?p ?o
WHERE {
    fountain:FUE_01_0007 ?p ?o
}

SELECT ?p ?o
WHERE {
    district:LATINA ?p ?o
}

