PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#> 

  # Query to find, for a given starting class ?tree0 (in this case Q14941854),
  # what properties are registered as normally applying
  # to it, or to a super-class of it
  # Query generated by [[Template:PropertyForThisType]]

SELECT ?class ?classname ?property ?propertyname WHERE {
  ?tree0 (wdt:P279)* ?class .	--tree0 es subclase de class
  BIND (wd:Q82955 AS ?tree0)
  ?class wdt:P1963 ?property .
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "en" .
    ?class rdfs:label ?classname .
    ?property rdfs:label ?propertyname .
  }
}


-- primera
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#> 

  # Query to find, for a given starting class ?tree0 (in this case Q14941854),
  # what properties are registered as normally applying
  # to it, or to a super-class of it
  # Query generated by [[Template:PropertyForThisType]]

SELECT ?class ?classname ?property ?propertyname WHERE {
  BIND (wd:Q82955 AS ?class)
  ?class wdt:P1963 ?property .
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "en" .
    ?class rdfs:label ?classname .
    ?property rdfs:label ?propertyname .
  }
}