PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rc: <http://smartcity.smartbins.es/lcc/ontology/recycle#>
    
#QUERY 1: BINS

SELECT DISTINCT ?Bin WHERE{
        ?Bin rdf:type rc:Bin.
    }

#http://smartcity.smartbins.es/lcc/resource/Bin/1523159
#http://smartcity.smartbins.es/lcc/resource/Bin/1523493
#http://smartcity.smartbins.es/lcc/resource/Bin/1523138
#http://smartcity.smartbins.es/lcc/resource/Bin/1523472
#http://smartcity.smartbins.es/lcc/resource/Bin/1523117
#http://smartcity.smartbins.es/lcc/resource/Bin/1523280
#http://smartcity.smartbins.es/lcc/resource/Bin/1523259
#http://smartcity.smartbins.es/lcc/resource/Bin/1523359
#http://smartcity.smartbins.es/lcc/resource/Bin/1522416
#http://smartcity.smartbins.es/lcc/resource/Bin/1523004
#http://smartcity.smartbins.es/lcc/resource/Bin/1523188
#http://smartcity.smartbins.es/lcc/resource/Bin/1523167
#http://smartcity.smartbins.es/lcc/resource/Bin/1523317
#http://smartcity.smartbins.es/lcc/resource/Bin/1523125
#http://smartcity.smartbins.es/lcc/resource/Bin/1521210
#http://smartcity.smartbins.es/lcc/resource/Bin/1523267
#http://smartcity.smartbins.es/lcc/resource/Bin/1523225
#http://smartcity.smartbins.es/lcc/resource/Bin/1522992
#http://smartcity.smartbins.es/lcc/resource/Bin/1523175
#http://smartcity.smartbins.es/lcc/resource/Bin/1523112
#http://smartcity.smartbins.es/lcc/resource/Bin/1523296
#http://smartcity.smartbins.es/lcc/resource/Bin/1523254
#http://smartcity.smartbins.es/lcc/resource/Bin/1523233
#http://smartcity.smartbins.es/lcc/resource/Bin/1523183
#http://smartcity.smartbins.es/lcc/resource/Bin/1517391
#http://smartcity.smartbins.es/lcc/resource/Bin/1523162
#http://smartcity.smartbins.es/lcc/resource/Bin/1523504
#http://smartcity.smartbins.es/lcc/resource/Bin/1523141
#http://smartcity.smartbins.es/lcc/resource/Bin/1523496
#http://smartcity.smartbins.es/lcc/resource/Bin/1523120
#http://smartcity.smartbins.es/lcc/resource/Bin/1523262
#http://smartcity.smartbins.es/lcc/resource/Bin/1522987
#http://smartcity.smartbins.es/lcc/resource/Bin/1523007
#http://smartcity.smartbins.es/lcc/resource/Bin/1523512
#http://smartcity.smartbins.es/lcc/resource/Bin/1523149
#http://smartcity.smartbins.es/lcc/resource/Bin/1523128
#http://smartcity.smartbins.es/lcc/resource/Bin/1523483
#http://smartcity.smartbins.es/lcc/resource/Bin/1523228
#http://smartcity.smartbins.es/lcc/resource/Bin/1523207
#http://smartcity.smartbins.es/lcc/resource/Bin/1523199
#http://smartcity.smartbins.es/lcc/resource/Bin/1523178
#http://smartcity.smartbins.es/lcc/resource/Bin/1523520
#http://smartcity.smartbins.es/lcc/resource/Bin/1523328
#http://smartcity.smartbins.es/lcc/resource/Bin/1523115
#http://smartcity.smartbins.es/lcc/resource/Bin/1522882
#http://smartcity.smartbins.es/lcc/resource/Bin/1522982
#http://smartcity.smartbins.es/lcc/resource/Bin/1523186
#http://smartcity.smartbins.es/lcc/resource/Bin/1523507
#http://smartcity.smartbins.es/lcc/resource/Bin/1523144
#http://smartcity.smartbins.es/lcc/resource/Bin/1523123
#http://smartcity.smartbins.es/lcc/resource/Bin/1523244
#http://smartcity.smartbins.es/lcc/resource/Bin/1523202
#http://smartcity.smartbins.es/lcc/resource/Bin/1523010
#http://smartcity.smartbins.es/lcc/resource/Bin/1523152
#http://smartcity.smartbins.es/lcc/resource/Bin/1523486
#http://smartcity.smartbins.es/lcc/resource/Bin/1523252
#http://smartcity.smartbins.es/lcc/resource/Bin/1522998
#http://smartcity.smartbins.es/lcc/resource/Bin/1523210
#http://smartcity.smartbins.es/lcc/resource/Bin/1523352
#http://smartcity.smartbins.es/lcc/resource/Bin/1523502
#http://smartcity.smartbins.es/lcc/resource/Bin/1523139
#http://smartcity.smartbins.es/lcc/resource/Bin/1523118
#http://smartcity.smartbins.es/lcc/resource/Bin/1523473
#http://smartcity.smartbins.es/lcc/resource/Bin/1523260
#http://smartcity.smartbins.es/lcc/resource/Bin/1523239
#http://smartcity.smartbins.es/lcc/resource/Bin/1523218
#http://smartcity.smartbins.es/lcc/resource/Bin/1523360
#http://smartcity.smartbins.es/lcc/resource/Bin/1523168
#http://smartcity.smartbins.es/lcc/resource/Bin/1523147
#http://smartcity.smartbins.es/lcc/resource/Bin/1523481
#http://smartcity.smartbins.es/lcc/resource/Bin/1523247
#http://smartcity.smartbins.es/lcc/resource/Bin/1522993
#http://smartcity.smartbins.es/lcc/resource/Bin/1523155
#http://smartcity.smartbins.es/lcc/resource/Bin/1523113
#http://smartcity.smartbins.es/lcc/resource/Bin/1523276
#http://smartcity.smartbins.es/lcc/resource/Bin/1523255
#http://smartcity.smartbins.es/lcc/resource/Bin/1523234
#http://smartcity.smartbins.es/lcc/resource/Bin/1523213
#http://smartcity.smartbins.es/lcc/resource/Bin/1523000
#http://smartcity.smartbins.es/lcc/resource/Bin/1523184
#http://smartcity.smartbins.es/lcc/resource/Bin/1523163
#http://smartcity.smartbins.es/lcc/resource/Bin/1523505
#http://smartcity.smartbins.es/lcc/resource/Bin/1523142
#http://smartcity.smartbins.es/lcc/resource/Bin/1523121
#http://smartcity.smartbins.es/lcc/resource/Bin/1522846
#http://smartcity.smartbins.es/lcc/resource/Bin/1523221
#http://smartcity.smartbins.es/lcc/resource/Bin/1522988
#http://smartcity.smartbins.es/lcc/resource/Bin/1523008
#http://smartcity.smartbins.es/lcc/resource/Bin/1523513
#http://smartcity.smartbins.es/lcc/resource/Bin/1523129
#http://smartcity.smartbins.es/lcc/resource/Bin/1523292
#http://smartcity.smartbins.es/lcc/resource/Bin/1522996
#http://smartcity.smartbins.es/lcc/resource/Bin/1523208
#http://smartcity.smartbins.es/lcc/resource/Bin/1523521
#http://smartcity.smartbins.es/lcc/resource/Bin/1523158
#http://smartcity.smartbins.es/lcc/resource/Bin/1523329
#http://smartcity.smartbins.es/lcc/resource/Bin/1523492
#http://smartcity.smartbins.es/lcc/resource/Bin/1523308
#http://smartcity.smartbins.es/lcc/resource/Bin/1523116
#http://smartcity.smartbins.es/lcc/resource/Bin/1523279
#http://smartcity.smartbins.es/lcc/resource/Bin/1523216
#http://smartcity.smartbins.es/lcc/resource/Bin/1523003
#http://smartcity.smartbins.es/lcc/resource/Bin/1523187
#http://smartcity.smartbins.es/lcc/resource/Bin/1523508
#http://smartcity.smartbins.es/lcc/resource/Bin/1523479
#http://smartcity.smartbins.es/lcc/resource/Bin/1523224
#http://smartcity.smartbins.es/lcc/resource/Bin/1522991
#http://smartcity.smartbins.es/lcc/resource/Bin/1523195
#http://smartcity.smartbins.es/lcc/resource/Bin/1523516
#http://smartcity.smartbins.es/lcc/resource/Bin/1523466
#http://smartcity.smartbins.es/lcc/resource/Bin/1523253
#http://smartcity.smartbins.es/lcc/resource/Bin/1523211
#http://smartcity.smartbins.es/lcc/resource/Bin/1523182
#http://smartcity.smartbins.es/lcc/resource/Bin/1523140
#http://smartcity.smartbins.es/lcc/resource/Bin/1523119
#http://smartcity.smartbins.es/lcc/resource/Bin/1522886
#http://smartcity.smartbins.es/lcc/resource/Bin/1523282
#http://smartcity.smartbins.es/lcc/resource/Bin/1523261
#http://smartcity.smartbins.es/lcc/resource/Bin/1523240
#http://smartcity.smartbins.es/lcc/resource/Bin/1522986
#http://smartcity.smartbins.es/lcc/resource/Bin/1523006
#http://smartcity.smartbins.es/lcc/resource/Bin/1523511
#http://smartcity.smartbins.es/lcc/resource/Bin/1523319
#http://smartcity.smartbins.es/lcc/resource/Bin/1523127
#http://smartcity.smartbins.es/lcc/resource/Bin/1523248
#http://smartcity.smartbins.es/lcc/resource/Bin/1522994
#http://smartcity.smartbins.es/lcc/resource/Bin/1523198
#http://smartcity.smartbins.es/lcc/resource/Bin/1523519
#http://smartcity.smartbins.es/lcc/resource/Bin/1523135
#http://smartcity.smartbins.es/lcc/resource/Bin/1523114
#http://smartcity.smartbins.es/lcc/resource/Bin/1523298
#http://smartcity.smartbins.es/lcc/resource/Bin/1523256
#http://smartcity.smartbins.es/lcc/resource/Bin/1523235
#http://smartcity.smartbins.es/lcc/resource/Bin/1522981
#http://smartcity.smartbins.es/lcc/resource/Bin/1523356
#http://smartcity.smartbins.es/lcc/resource/Bin/1523185
#http://smartcity.smartbins.es/lcc/resource/Bin/1523164
#http://smartcity.smartbins.es/lcc/resource/Bin/1523506
#http://smartcity.smartbins.es/lcc/resource/Bin/1523143
#http://smartcity.smartbins.es/lcc/resource/Bin/1523122
#http://smartcity.smartbins.es/lcc/resource/Bin/1522889
#http://smartcity.smartbins.es/lcc/resource/Bin/1523285
#http://smartcity.smartbins.es/lcc/resource/Bin/1523243
#http://smartcity.smartbins.es/lcc/resource/Bin/1523222
#http://smartcity.smartbins.es/lcc/resource/Bin/1523201
#http://smartcity.smartbins.es/lcc/resource/Bin/1522989
#http://smartcity.smartbins.es/lcc/resource/Bin/1523193
#http://smartcity.smartbins.es/lcc/resource/Bin/1522968
#http://smartcity.smartbins.es/lcc/resource/Bin/1523009
#http://smartcity.smartbins.es/lcc/resource/Bin/1523130
#http://smartcity.smartbins.es/lcc/resource/Bin/1523485
#http://smartcity.smartbins.es/lcc/resource/Bin/1523293
#http://smartcity.smartbins.es/lcc/resource/Bin/1523464
#http://smartcity.smartbins.es/lcc/resource/Bin/1523230
#http://smartcity.smartbins.es/lcc/resource/Bin/1522997
#http://smartcity.smartbins.es/lcc/resource/Bin/1523522
#http://smartcity.smartbins.es/lcc/resource/Bin/1523501

#QUERY 2: PRODUCTS

SELECT DISTINCT ?Product WHERE{
        ?Product rdf:type rc:Product.
    } ORDER BY asc(?Product)

#http://smartcity.smartbins.es/lcc/resource/Product/1
#http://smartcity.smartbins.es/lcc/resource/Product/10
#http://smartcity.smartbins.es/lcc/resource/Product/100
#http://smartcity.smartbins.es/lcc/resource/Product/101
#http://smartcity.smartbins.es/lcc/resource/Product/102
#http://smartcity.smartbins.es/lcc/resource/Product/103
#http://smartcity.smartbins.es/lcc/resource/Product/104
#http://smartcity.smartbins.es/lcc/resource/Product/105
#http://smartcity.smartbins.es/lcc/resource/Product/106
#http://smartcity.smartbins.es/lcc/resource/Product/107
#http://smartcity.smartbins.es/lcc/resource/Product/108
#http://smartcity.smartbins.es/lcc/resource/Product/109
#http://smartcity.smartbins.es/lcc/resource/Product/11
#http://smartcity.smartbins.es/lcc/resource/Product/110
#http://smartcity.smartbins.es/lcc/resource/Product/111
#http://smartcity.smartbins.es/lcc/resource/Product/112
#http://smartcity.smartbins.es/lcc/resource/Product/113
#http://smartcity.smartbins.es/lcc/resource/Product/114
#http://smartcity.smartbins.es/lcc/resource/Product/115
#http://smartcity.smartbins.es/lcc/resource/Product/116
#http://smartcity.smartbins.es/lcc/resource/Product/117
#http://smartcity.smartbins.es/lcc/resource/Product/118
#http://smartcity.smartbins.es/lcc/resource/Product/119
#http://smartcity.smartbins.es/lcc/resource/Product/12
#http://smartcity.smartbins.es/lcc/resource/Product/120
#http://smartcity.smartbins.es/lcc/resource/Product/121
#http://smartcity.smartbins.es/lcc/resource/Product/122
#http://smartcity.smartbins.es/lcc/resource/Product/123
#http://smartcity.smartbins.es/lcc/resource/Product/124
#http://smartcity.smartbins.es/lcc/resource/Product/125
#http://smartcity.smartbins.es/lcc/resource/Product/126
#http://smartcity.smartbins.es/lcc/resource/Product/127
#http://smartcity.smartbins.es/lcc/resource/Product/128
#http://smartcity.smartbins.es/lcc/resource/Product/129
#http://smartcity.smartbins.es/lcc/resource/Product/13
#http://smartcity.smartbins.es/lcc/resource/Product/130
#http://smartcity.smartbins.es/lcc/resource/Product/131
#http://smartcity.smartbins.es/lcc/resource/Product/132
#http://smartcity.smartbins.es/lcc/resource/Product/133
#http://smartcity.smartbins.es/lcc/resource/Product/134
#http://smartcity.smartbins.es/lcc/resource/Product/135
#http://smartcity.smartbins.es/lcc/resource/Product/14
#http://smartcity.smartbins.es/lcc/resource/Product/15
#http://smartcity.smartbins.es/lcc/resource/Product/16
#http://smartcity.smartbins.es/lcc/resource/Product/17
#http://smartcity.smartbins.es/lcc/resource/Product/18
#http://smartcity.smartbins.es/lcc/resource/Product/19
#http://smartcity.smartbins.es/lcc/resource/Product/2
#http://smartcity.smartbins.es/lcc/resource/Product/20
#http://smartcity.smartbins.es/lcc/resource/Product/21
#http://smartcity.smartbins.es/lcc/resource/Product/22
#http://smartcity.smartbins.es/lcc/resource/Product/23
#http://smartcity.smartbins.es/lcc/resource/Product/24
#http://smartcity.smartbins.es/lcc/resource/Product/25
#http://smartcity.smartbins.es/lcc/resource/Product/26
#http://smartcity.smartbins.es/lcc/resource/Product/27
#http://smartcity.smartbins.es/lcc/resource/Product/28
#http://smartcity.smartbins.es/lcc/resource/Product/283
#http://smartcity.smartbins.es/lcc/resource/Product/284
#http://smartcity.smartbins.es/lcc/resource/Product/285
#http://smartcity.smartbins.es/lcc/resource/Product/29
#http://smartcity.smartbins.es/lcc/resource/Product/3
#http://smartcity.smartbins.es/lcc/resource/Product/30
#http://smartcity.smartbins.es/lcc/resource/Product/31
#http://smartcity.smartbins.es/lcc/resource/Product/32
#http://smartcity.smartbins.es/lcc/resource/Product/33
#http://smartcity.smartbins.es/lcc/resource/Product/34
#http://smartcity.smartbins.es/lcc/resource/Product/35
#http://smartcity.smartbins.es/lcc/resource/Product/36
#http://smartcity.smartbins.es/lcc/resource/Product/37
#http://smartcity.smartbins.es/lcc/resource/Product/38
#http://smartcity.smartbins.es/lcc/resource/Product/39
#http://smartcity.smartbins.es/lcc/resource/Product/4
#http://smartcity.smartbins.es/lcc/resource/Product/40
#http://smartcity.smartbins.es/lcc/resource/Product/41
#http://smartcity.smartbins.es/lcc/resource/Product/42
#http://smartcity.smartbins.es/lcc/resource/Product/43
#http://smartcity.smartbins.es/lcc/resource/Product/44
#http://smartcity.smartbins.es/lcc/resource/Product/45
#http://smartcity.smartbins.es/lcc/resource/Product/46
#http://smartcity.smartbins.es/lcc/resource/Product/47
#http://smartcity.smartbins.es/lcc/resource/Product/48
#http://smartcity.smartbins.es/lcc/resource/Product/49
#http://smartcity.smartbins.es/lcc/resource/Product/5
#http://smartcity.smartbins.es/lcc/resource/Product/50
#http://smartcity.smartbins.es/lcc/resource/Product/51
#http://smartcity.smartbins.es/lcc/resource/Product/52
#http://smartcity.smartbins.es/lcc/resource/Product/53
#http://smartcity.smartbins.es/lcc/resource/Product/54
#http://smartcity.smartbins.es/lcc/resource/Product/55
#http://smartcity.smartbins.es/lcc/resource/Product/56
#http://smartcity.smartbins.es/lcc/resource/Product/57
#http://smartcity.smartbins.es/lcc/resource/Product/58
#http://smartcity.smartbins.es/lcc/resource/Product/59
#http://smartcity.smartbins.es/lcc/resource/Product/6
#http://smartcity.smartbins.es/lcc/resource/Product/60
#http://smartcity.smartbins.es/lcc/resource/Product/61
#http://smartcity.smartbins.es/lcc/resource/Product/62
#http://smartcity.smartbins.es/lcc/resource/Product/63
#http://smartcity.smartbins.es/lcc/resource/Product/64
#http://smartcity.smartbins.es/lcc/resource/Product/65
#http://smartcity.smartbins.es/lcc/resource/Product/66
#http://smartcity.smartbins.es/lcc/resource/Product/67
#http://smartcity.smartbins.es/lcc/resource/Product/68
#http://smartcity.smartbins.es/lcc/resource/Product/69
#http://smartcity.smartbins.es/lcc/resource/Product/7
#http://smartcity.smartbins.es/lcc/resource/Product/70
#http://smartcity.smartbins.es/lcc/resource/Product/71
#http://smartcity.smartbins.es/lcc/resource/Product/72
#http://smartcity.smartbins.es/lcc/resource/Product/73
#http://smartcity.smartbins.es/lcc/resource/Product/74
#http://smartcity.smartbins.es/lcc/resource/Product/75
#http://smartcity.smartbins.es/lcc/resource/Product/76
#http://smartcity.smartbins.es/lcc/resource/Product/77
#http://smartcity.smartbins.es/lcc/resource/Product/78
#http://smartcity.smartbins.es/lcc/resource/Product/79
#http://smartcity.smartbins.es/lcc/resource/Product/8
#http://smartcity.smartbins.es/lcc/resource/Product/80
#http://smartcity.smartbins.es/lcc/resource/Product/81
#http://smartcity.smartbins.es/lcc/resource/Product/82
#http://smartcity.smartbins.es/lcc/resource/Product/83
#http://smartcity.smartbins.es/lcc/resource/Product/84
#http://smartcity.smartbins.es/lcc/resource/Product/85
#http://smartcity.smartbins.es/lcc/resource/Product/86
#http://smartcity.smartbins.es/lcc/resource/Product/87
#http://smartcity.smartbins.es/lcc/resource/Product/88
#http://smartcity.smartbins.es/lcc/resource/Product/89
#http://smartcity.smartbins.es/lcc/resource/Product/9
#http://smartcity.smartbins.es/lcc/resource/Product/90
#http://smartcity.smartbins.es/lcc/resource/Product/91
#http://smartcity.smartbins.es/lcc/resource/Product/92
#http://smartcity.smartbins.es/lcc/resource/Product/93
#http://smartcity.smartbins.es/lcc/resource/Product/94
#http://smartcity.smartbins.es/lcc/resource/Product/95
#http://smartcity.smartbins.es/lcc/resource/Product/96
#http://smartcity.smartbins.es/lcc/resource/Product/97
#http://smartcity.smartbins.es/lcc/resource/Product/98
#http://smartcity.smartbins.es/lcc/resource/Product/99