PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX clase: <http://localizalocales.es/lcc/ontology/locales#>.


SELECT DISTINCT
        ?Object 
    WHERE {
        ?Accident clase:numeroMesasAutorizadas ?Object.
    }

(rdflib.term.Literal('5'),)
(rdflib.term.Literal(''),)
(rdflib.term.Literal('9'),)
(rdflib.term.Literal('4'),)
(rdflib.term.Literal('5'),)
(rdflib.term.Literal('8'),)
